#!/usr/bin/env python3
"""Generate an RGBDS INCBIN baseline from a local Game Boy ROM.

The ROM itself is never copied into the repository. The generated assembly contains
only SECTION declarations and INCBIN ranges pointing at the local ROM path.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

BANK_SIZE = 0x4000


def sha1(data: bytes) -> str:
    return hashlib.sha1(data).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("rom", type=Path)
    parser.add_argument("--output", type=Path, default=Path("src/banks.asm"))
    parser.add_argument("--manifest", type=Path, default=Path("out/incbin-banks.json"))
    args = parser.parse_args()

    data = args.rom.read_bytes()
    if not data or len(data) % BANK_SIZE:
        raise SystemExit(
            f"ROM size must be a non-zero multiple of 0x{BANK_SIZE:X}; got 0x{len(data):X}"
        )

    bank_count = len(data) // BANK_SIZE
    rom_ref = args.rom.as_posix().replace('"', '\\"')

    lines = [
        "; Auto-generated by tools/bootstrap_incbin.py.",
        "; Do not hand-edit: replace INCBIN ranges with reconstructed source progressively.",
        "",
    ]
    banks = []

    for bank in range(bank_count):
        start = bank * BANK_SIZE
        chunk = data[start : start + BANK_SIZE]
        if bank == 0:
            lines.append('SECTION "ROM Bank 000", ROM0[$0000]')
        else:
            lines.append(f'SECTION "ROM Bank {bank:03X}", ROMX[$4000], BANK[${bank:02X}]')
        lines.append(f'INCBIN "{rom_ref}", ${start:06X}, ${BANK_SIZE:04X}')
        lines.append("")
        banks.append(
            {
                "bank": bank,
                "start": start,
                "size": BANK_SIZE,
                "sha1": sha1(chunk),
            }
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")

    manifest = {
        "source_file": args.rom.name,
        "size": len(data),
        "sha1": sha1(data),
        "bank_size": BANK_SIZE,
        "bank_count": bank_count,
        "banks": banks,
    }
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"generated {args.output} for {bank_count} banks")
    print(f"ROM SHA-1: {manifest['sha1']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
