; Generated by tools/disassemble_gb_cfg.py; do not edit by hand.

SECTION "Entry CFG 05c5", ROM0[$05c5]

Block_05c5::
    cp $11
    jr z $05cc

SECTION "Entry CFG 05c9", ROM0[$05c9]

Block_05c9::
    xor a
    jr $05ce

SECTION "Entry CFG 05cc", ROM0[$05cc]

Block_05cc::
    ld a, $01
    ldh [$ff00 + $e8], a
    di
    xor a
    ldh [$ff00 + $0f], a
    ldh [$ff00 + $ff], a
    ldh [$ff00 + $56], a
    ldh [$ff00 + $43], a
    ldh [$ff00 + $42], a
    ldh [$ff00 + $01], a
    ldh [$ff00 + $02], a
    ldh [$ff00 + $4b], a
    ldh [$ff00 + $4a], a
    ldh [$ff00 + $47], a
    ldh [$ff00 + $48], a
    ldh [$ff00 + $49], a
    ldh [$ff00 + $06], a
    ldh [$ff00 + $07], a
    ld [$cf1f], a
    ld a, $04
    ldh [$ff00 + $07], a
    ldh a, [$ff00 + $44]
    cp $91
    jr nz $05f5
