; Generated by tools/disassemble_gb_cfg.py; do not edit by hand.

SECTION "FR Startup CFG 05c6", ROM0[$05c6]

Block_05c6::
    cp $11
    jr z $05cd

SECTION "FR Startup CFG 05ca", ROM0[$05ca]

Block_05ca::
    xor a
    jr $05cf

SECTION "FR Startup CFG 05cd", ROM0[$05cd]

Block_05cd::
    ld a, $01

SECTION "FR Startup CFG 05cf", ROM0[$05cf]

Block_05cf::
    ldh [$ff00 + $e8], a
    di
    xor a
    ldh [$ff00 + $0f], a
    ldh [$ff00 + $ff], a
    ldh [$ff00 + $56], a
    ldh [$ff00 + $43], a
    ldh [$ff00 + $42], a
    ldh [$ff00 + $01], a
    ldh [$ff00 + $02], a
    ldh [$ff00 + $4b], a
    ldh [$ff00 + $4a], a
    ldh [$ff00 + $47], a
    ldh [$ff00 + $48], a
    ldh [$ff00 + $49], a
    ldh [$ff00 + $06], a
    ldh [$ff00 + $07], a
    ld [$ceeb], a
    ld a, $04
    ldh [$ff00 + $07], a
    ldh a, [$ff00 + $44]
    cp $91
    jr nz $05f6

SECTION "FR Startup CFG 05fc", ROM0[$05fc]

Block_05fc::
    xor a
    ldh [$ff00 + $40], a
    ld hl, $c000
    ld bc, $2000
    ld [hl], $00
    inc hl
    dec bc
    ld a, b
    or c
    jr nz $0605
