; Generated by tools/disassemble_gb_cfg.py; do not edit by hand.

SECTION "Korean Startup CFG 05ca", ROM0[$05ca]

Block_05ca::
    cp $11
    jr z $05d3

SECTION "Korean Startup CFG 05ce", ROM0[$05ce]

Block_05ce::
    xor a
    ldh [$ff00 + $e8], a
    jr $05dc

SECTION "Korean Startup CFG 05d3", ROM0[$05d3]

Block_05d3::
    ld a, $01
    ldh [$ff00 + $e8], a
    bit 0, b
    jr nz $05dc

SECTION "Korean Startup CFG 05db", ROM0[$05db]

Block_05db::
    xor a

SECTION "Korean Startup CFG 05dc", ROM0[$05dc]

Block_05dc::
    ldh [$ff00 + $ea], a
    di
    xor a
    ldh [$ff00 + $0f], a
    ldh [$ff00 + $ff], a
    ldh [$ff00 + $56], a
    ldh [$ff00 + $43], a
    ldh [$ff00 + $42], a
    ldh [$ff00 + $01], a
    ldh [$ff00 + $02], a
    ldh [$ff00 + $4b], a
    ldh [$ff00 + $4a], a
    ldh [$ff00 + $47], a
    ldh [$ff00 + $48], a
    ldh [$ff00 + $49], a
    ldh [$ff00 + $06], a
    ldh [$ff00 + $07], a
    ld [$cec0], a
    ld a, $04
    ldh [$ff00 + $07], a
    ldh a, [$ff00 + $44]
    cp $91
    jr nz $0603

SECTION "Korean Startup CFG 0609", ROM0[$0609]

Block_0609::
    xor a
    ldh [$ff00 + $40], a
    ld hl, $c000
    ld bc, $2000
    ld [hl], $00
    inc hl
    dec bc
    ld a, b
    or c
    jr nz $0612
